# Generated by Django 5.2.15 on 2026-06-09 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_type', models.CharField(choices=[('department', 'Department'), ('club', 'Club')], max_length=20)),
                ('status', models.CharField(choices=[('pending_hod', 'Pending HOD'), ('pending_ed', 'Pending ED'), ('returned_to_staff', 'Returned To Staff'), ('returned_to_hod', 'Returned To HOD'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('programme_name', models.CharField(max_length=255)),
                ('requisition_date', models.DateField()),
                ('programme_datetime', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('target_audience', models.CharField(blank=True, max_length=255)),
                ('resource_person_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.department')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved_by_hod', 'Approved By HOd'), ('rejected_by_hod', 'Rejected By Hod'), ('returned_by_hod', 'Returned By HOD'), ('approved_by_ed', 'Approved By ED'), ('rejected_by_ed', 'Rejected By ED'), ('returned_by_ed', 'Returned By ED'), ('resubmitted', 'Resubmitted')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='user_module.requisition')),
            ],
            options={
                'ordering': ['acted_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='requisition_documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user_module.requisition')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.PositiveIntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('specification', models.TextField(blank=True, null=True)),
                ('required_quantity', models.PositiveIntegerField()),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user_module.requisition')),
            ],
            options={
                'ordering': ['sl_no'],
                'unique_together': {('requisition', 'sl_no')},
            },
        ),
    ]
