# Generated by Django 5.2.15 on 2026-06-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_hod', 'Pending HOD'), ('pending_ed', 'Pending ED'), ('returned_to_staff', 'Returned To Staff'), ('returned_to_hod', 'Returned To HOD'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30),
        ),
    ]
