# Generated by Django 5.2.15 on 2026-06-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_alter_requisition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='resource_person_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='venue',
            field=models.CharField(max_length=255),
        ),
    ]
