# Generated by Django 4.2.28 on 2026-06-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_alter_requisition_resource_person_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='ed_sign_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='requisition',
            name='ed_signature',
            field=models.ImageField(blank=True, null=True, upload_to='req_signatures/'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='ed_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='hod_sign_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='requisition',
            name='hod_signature',
            field=models.ImageField(blank=True, null=True, upload_to='req_signatures/'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='hod_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='staff_sign_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='requisition',
            name='staff_signature',
            field=models.ImageField(blank=True, null=True, upload_to='req_signatures/'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='staff_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
